# Generated by Django 5.2.16 on 2026-07-15 12:02

import cv.models
import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_gamemap_high_score_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cv.models.generate_room_code, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('playing', 'Playing'), ('results', 'Results'), ('closed', 'Closed')], default='lobby', max_length=20)),
                ('current_round_started_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_rooms', to='cv.gamemap')),
            ],
        ),
        migrations.CreateModel(
            name='PartyPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('color', models.CharField(max_length=7)),
                ('session_token', models.CharField(default=secrets.token_urlsafe, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cv.partyroom')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
    ]
