# Generated by Django 5.2.16 on 2026-07-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_partyroom_partyplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMapSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_submissions', to='cv.gamemap')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_submissions', to='cv.partyplayer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_submissions', to='cv.partyroom')),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
    ]
