# Generated by Django 5.2.16 on 2026-07-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_partymapsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRoundResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(max_length=80)),
                ('finish_ms', models.IntegerField(blank=True, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_round_results', to='cv.gamemap')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='cv.partyplayer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='cv.partyroom')),
            ],
            options={
                'ordering': ['-created', '-score'],
                'constraints': [models.UniqueConstraint(fields=('room', 'player', 'round_id'), name='unique_party_round_result')],
            },
        ),
    ]
